# -*- coding: utf-8 -*-
"""Copy of Predictive Modelling with Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bn03IL2fCh1B_t-MmFdOhHxA4j3-yj4a
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from pandas.core.common import random_state
from sklearn.linear_model import LinearRegression

df_sal = pd.read_csv('/content/employee_salary.csv')
df_sal.head()

df_sal.describe()

plt.title('Salary Distribution Plot')
sns.histplot(df_sal['Salary'])
plt.show()

plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.scatter(df_sal['YearsExperience'],df_sal['Salary'])
plt.show()

X = df_sal.iloc[:, :1]
y = df_sal.iloc[:, 1:]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred_test = regressor.predict(X_test)
y_pred_train = regressor.predict(X_train)

plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.legend(['X_train/Pred(y_test)', 'X_train/y_train'], title = 'Sal/Exp', loc='best', facecolor='white')
plt.scatter(X_train, y_train)
plt.plot(X_train, y_pred_train)

plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.legend(['X_train/Pred(y_test)', 'X_train/y_train'], title = 'Sal/Exp', loc='best', facecolor='white')
plt.scatter(X_test, y_test)
plt.plot(X_train, y_pred_train)